# Generated by Django 3.1.4 on 2021-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dimension', models.CharField(max_length=30)),
                ('colours', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=30)),
                ('image', models.TextField()),
            ],
        ),
    ]
