# Generated by Django 3.1.4 on 2021-02-10 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210210_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='seen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
